# use_logo如果为true, 需要在logo_image设置路径
use_logo: false
logo_image:  # 使用路径, 填写文件名即可(比如, logo_image: logo.png 指向 source/imgs/logo.png)
navbar_text: # 如果没有Logo, 则设置为false, 并且设置navbar_text(否则默认为站点标题, 最好进行设置)

# 必填, 设定小型设备展示背景图, 指向source/imgs, 比如xs_bg_image: bg.png -> source/imgs/bg.png
xs_bg_image: xsbg.gif

# 必填, 个人头像, 如果是路径, 则指向source/imgs
# 也可以填http:// OR https:// url地址
author_image: avatar.jpg

# 程序员模式, 适合于用该程序的爱好写技术文章的人员, 默认不开启
# 选择开启后将会改变article-excerpt, article-content等的显示
programmer_mode: false

# 导航菜单
menu:
  # index
  - title: 首页
    # 参照font-awesome官网的icon, 取后面一段(比如用fa-star这个图标, 那么这里的icon就填star)
    icon: home
    url: /
  # archives
  - title: 归档
    icon: archive
    url: archives
  # categories (已隐藏)
  # - title: 分类
  #   icon: list
  #   url: categories
  #   dropdown: 3
  # tags (已隐藏)
  # - title: 标签
  #   icon: tags
  #   url: tags
  #   dropdown: 3
  # wallpaper
  - title: 壁纸
    icon: image
    url: wallpaper
  # about, 这个实际上是自定义page, 后面的自定义page参照about样式
  - title: 关于我
    icon: user
    url: about

# 每篇文章的preview默认图片
# 必填项(除非你每篇文章的front-matter都设置了preview属性)
# 填写: 可以放多张图, 将随机抽取作为默认的preview图片
# 如果使用文件名则对应目录: source/imgs/preview, 比如 preview1.jpg -> source/imgs/preview/preview1.jpg
# 如果用url则填写完整的url地址即可
default_preview:
  # 是否使用API模式获取封面图
  use_api: true
  # 本地图片列表（use_api为false时使用）
  images:
    - preview1.jpg
    - preview2.jpg
    - preview3.jpg
    - preview4.jpg
  # API地址列表（use_api为true时使用，随机选择一个API）
  api_urls:
    - https://t.alcy.cc/ycy
    - https://t.alcy.cc/ysz
    - https://t.alcy.cc/pc
    - https://t.alcy.cc/moe
    - https://t.alcy.cc/fj

# 侧边栏
sidebar:
  recent_comments: false   # 最新评论, 默认关闭, 可能需要自己进行模板配置
  hot_posts: true         # 最热文章, 如果配置了下面的文章统计就可以使用该侧边栏, 否则设置为false
  recent_posts: true      # 最新文章, 默认开启
  random_posts: true      # 随机文章, 默认开启
  tags: true              # 热门标签, 默认开启
  friend_links: true      # 友情链接, 默认开启
  links: true             # 个人链接, 默认开启

# 友情链接配置, 要先开启上面的friend_links
friend_links:
  - name: KDays Forum
    link: http://kdays.net/days/
  - name: 绅士导航♂
    link: http://www.gal123.com/
  - name: 萌导航
    link: http://www.moe123.com/

# 个人链接配置, 要先开启上面的links
links:
  - name: Github
    link: https://github.com/ZEROKISEKI/
  - name: Coding
    link: https://coding.net/u/SORA1
  - name: 知乎
    link: https://www.zhihu.com/people/aonosora/activities


# 是否使用公告
# 公告是什么可以看https://myau.moe
# 如果使用了公告, 那么公告内容需要自己去配置
# 在主题下的layout/_partial/issue.ejs进行内容修改
# 如果不用公告, 请设置此项为false
use_issue: false

# 指定代码高亮风格
# 目前支持以下选择
# github
# railscasts
# monokai_sublime
# atom-one-dark
# darcula
highlight_theme: atom-one-dark

# 背景图功能
# 必填项
slide_background:
  # 默认为false, 即采用路径图片
  use_url: false
  # use_url: false情况下, 采用本地博客图片路径, 下面三个参数组合指向: source/imgs/slide/background(1~37).jpg
  prefix: slide/background
  ext: jpg
  max_count: 37
  # API模式配置 - 设置use_api为true启用随机图片API
  use_api: true
  # API轮播图片数量（默认6张，可自定义）
  api_count: 6
  # API地址列表，支持多个API随机选择（高清二次元）
  api_urls:
    - https://t.alcy.cc/ycy
    - https://t.alcy.cc/ysz
    - https://t.alcy.cc/pc
    - https://t.alcy.cc/moe
    - https://t.alcy.cc/fj
    - https://t.alcy.cc/bd
    - https://t.alcy.cc/ys

# 壁纸页面配置
wallpaper:
  # PC端壁纸API列表
  pc_api_urls:
    - https://t.alcy.cc/ycy
    - https://t.alcy.cc/ysz
    - https://t.alcy.cc/pc
    - https://t.alcy.cc/moe
    - https://t.alcy.cc/fj
    - https://t.alcy.cc/bd
    - https://t.alcy.cc/ys
  # 手机端壁纸API列表（可后续添加）
  mobile_api_urls: []
  # 每次加载数量
  batch_size: 12
  # 最大加载数量
  max_images: 120

# 是否开启欧尼酱功能
open_oni: false
# 欧尼酱功能设置, 前提为open_oni: true
oni_setting:
  # 限三项, 可以自己配置链接(一般是上面的menu或者自己的page)
  - title: 归档
    url: archives
  - title: 关于
    url: about
  - title: 留言板
    url: message
# 欧尼酱选项图片(可以自己替换, 最好是100 * 100像素的图片)
# 图片为默认的 source/imgs/oni/oni(1~6).jpg
# 如果自己替换了不同后缀的图片, 需要在 source/css/_common.css中修改(直接ctrl + F搜oni)


# 输入特效activate-power-mode
# https://github.com/disjukr/activate-power-mode
power_mode:
  colorful: true
  shake: true

# 文章统计, 目前只支持leancloud(可能到时添加不蒜子统计)
# 获取appId和appKey方法直接百度 or google(或者看这篇http://crescentmoon.info/2014/12/11/popular-widget/)
# 注意一旦生成新的文章就不要随便改名了
leancloud:
  appid:  # yourappId
  appkey: # your appKeym

# 评论系统, 目前只支持gitment(为了自定义样式)
# 关于gitment如何配置看这篇 https://imsun.net/posts/gitment-introduction/
# 如果不用的话要把下面的use_comment设置为false
comment:
  gitment:
      owner: # 必填项, 你的GitHub ID
      repo: # 必填项  你的存储评论的repo
      oauth:
        client_id:  # 必填项
        client_secret: # 必填项
        redirect_uri: # 可以填也可以不填

# 是否使用评论系统
use_comment: false

# 音乐播放器配置
music_player:
  enable: true                    # 是否启用音乐播放器
  title: "歌单"                   # 播放器标题
  playlist_id: "8692231711"       # 歌单ID (腾讯音乐歌单ID)
  server: "tencent"               # 音乐服务器 (tencent/netease/kugou等)
  autoplay: false                 # 是否自动播放
  order: "list"                   # 播放顺序 (list/random)
  volume: 0.1                     # 默认音量 (0-1)
  theme: "#cc543a"                # 主题颜色
  list_folded: false              # 是否折叠播放列表

# 看板娘配置 (sakana-widget)
sakana_widget:
  enable: true                    # 是否启用看板娘
  position:                       # 位置配置
    bottom: "10px"                # 距离底部距离
    right: "10px"                 # 距离右侧距离

node_sass:
  outputStyle: compressed
  precision: 5
  sourceComments: false